### ISSUE TITLE
Default font settings makes it blurry

### ISSUE THREAD

**Issue by khurshid-alam** [sundarnagarajan/rdp-thinbook-linux#20]
I am using Ubuntu 17.10 unity session (installed from iso given) with latest xorg drivers. The default settings makes it slightly blurry. I used gnome-tweak-tool but unable to produce right display for me. Also my brightness is set to 39%.

![twek-tool-font-settingsbionic](https://user-images.githubusercontent.com/1333217/33806407-ad7dc686-dded-11e7-9b11-87c83f989702.png)

Turning off anti-aliasing makes it worse.

Do you recommend any particular settings for it?

**Comment by sundarnagarajan** [comment]
No
