### ISSUE TITLE
GPT partition scheme for uefi

### ISSUE THREAD

**Issue by vineetdurge123** [sundarnagarajan/rdp-thinbook-linux#29]
Will all your iso support gpt partiton for uefi. I didn't have ubantu to burn iso in my USB, should I use refus for creating one ?? Why 17.10 64 bit iso from official ubantu website support gpt partition for uefi and 16.04 do not. First I downloaded 17.10 iso, it detected USB in boot. But, shows error like 32bit.uefi not found. So downloaded 16.04 32 bit iso. But, it does not show USB in boot. Why sir ?? I think maybe MBR partition won't show in rdp thinbook. Only GPT shows. And refus show error that 16.04 iso is not gpt uefi bootable. Fix this pls.. I beg you sir ! Pls tell how to boot your iso in rdp. Should I try refus or what ??

**Comment by sundarnagarajan** [comment]
RDP Thinbook **ONLY** supports EFI. That means it **REQUIRES**:
- GPT partition table
- EFI partition
- EFI grub applications (bootia32.efi and bootx64.efi)

I have no idea about refus.

If you can find a utility in your current operating system that can copy a file (my ISO) to a disk device byte by byte, block by block, sector by sector starting with the first byte of the ISO file and starting with the first block / sector of the disk you want to write and proceeding to the end of the file, such a disk **should** work.

Unfortunately, my instructions will only work (or at least be easy to use) if:
- You have a working Linux environment / machine **already**
- You are fairly knowledgeable about Linux and are comfortable using command line tools

Sorry I could not be of more help. Perhaps you can contact a friend who has a Linux machine and is comfortable with Linux? Or a computer club near where you live.
