### ISSUE TITLE
Touchpad and TouchScreen Not working on RDP11.6 inch Thinbook

### ISSUE THREAD

**Issue by adam2161** [sundarnagarajan/rdp-thinbook-linux#34]
I've Installed Pre-compiled remastered iso  file in  Rdp 11.6 inch Thin Book ,But touchpad and Touchscreen not working.

**Comment by sundarnagarajan** [comment]
I don't believe the 11-inch model or the 14-inch model have touch screen
capability.

Can you elaborate?

**Comment by adam2161** [comment]
I'm having  ThinBook-360 (https://www.rdp.online/Laptops/ThinBook-360)  which has touch screen.
Touch worked perfectly on windows, But it not working on Linux , do i need to install any drivers or kernel patches?

**Comment by sundarnagarajan** [comment]
Sorry for the delay in responding.

I do not have any idea about the Thinbook 360. From the specs, it seems to use a Cherry Trail (Z8350)  SoC. However, the touchscreen is likely driven by some other hardware outside the Soc.

You **do** nee ddrivers. From my experience with a totally different convertible laptop - the [Chuwi Hi12](https://en.chuwi.com/product/items/Chuwi-Hi12.html), I found that (on **that** laptop):
- Ubuntu 16.04 had the required drivers - using my remastered ISO, booting of USB iinto a live session, the touchscreen worked perfectly.
- There are some (not yet figured out) "drivers" on a special partition - **outside** Windows that are **required** for the touchscreen to work in Linux
- While touchscreen works well, you still need to add some utilities in Linux to setup conveniences like right click menus, multi-finger gestures etc

You will be better off searching on the net for what works with the Chuwi Hi12 or similar touchscreen laptops
