### ISSUE TITLE
No bootup in linux

### ISSUE THREAD

**Issue by tanmaydwivedi** [sundarnagarajan/rdp-thinbook-linux#38]
Ubuntu 16.04.3
Installed on SSD (mmcblk0)
Yes created GPT partition table and EFI partition as well.
No error message at installation time.
OS installation was successful.
RDP 1430p laptop

Please help.

On boot up when i press F7, I find no device, screenshot attached
![img_20180215_224537](https://user-images.githubusercontent.com/36440756/36270971-2f5d8d3c-12a3-11e8-8d0d-7156c5bd339c.jpg)

_Originally posted by @darjihiren5188 in https://github.com/sundarnagarajan/rdp-thinbook-linux/issues/31#issuecomment-365999377_

**Comment by tanmaydwivedi** [comment]
Used your precompiled iso named ubuntu "Xenial Xerus 16.04.3", created a bootable pendrive using Rufus, and after successful dialog box, the laptop goes into bios instead of booting up linux.

**Comment by sundarnagarajan** [comment]
Hmm.... 
First of all - the UEFI / BIOS / firmware on this model has a limitation / bug that the different boot options - ESPECIALLY USB-attached disks - are not always shown when pressing F7 when machine is booting. This problem has no solution other than pressing CTRL-ALT-DEL and trying to boot again - usually it works on second or at most third try. But I have noticed this problem only for EXTERNAL USB-attached disks, and not for the onboard mmcblk0 EMMC

This appears to be a defect / bug in the upstream distribution not calling efibootmgr to add the boot entry

Fixing this requires you to be comfortable using the Linux command line from within the live ISO environment. You will need to know:

- The disk device name - usually /dev/mmcblk0 if you have installed on the onboard EMMC disk
- The partition number of the EFI partition within the onboard EMMC mmcblk0 disk - usually partition 1, but depends on how you chose to partition the disk

If you are comfortable with using the Linux command line, and I will send you more instructions

**Comment by tanmaydwivedi** [comment]
> Hmm....
> First of all - the UEFI / BIOS / firmware on this model has a limitation / bug that the different boot options - ESPECIALLY USB-attached disks - are not always shown when pressing F7 when machine is booting. This problem has no solution other than pressing CTRL-ALT-DEL and trying to boot again - usually it works on second or at most third try. But I have noticed this problem only for EXTERNAL USB-attached disks, and not for the onboard mmcblk0 EMMC
> 
> This appears to be a defect / bug in the upstream distribution not calling efibootmgr to add the boot entry
> 
> Fixing this requires you to be comfortable using the Linux command line from within the live ISO environment. You will need to know:
> 
> * The disk device name - usually /dev/mmcblk0 if you have installed on the onboard EMMC disk
> * The partition number of the EFI partition within the onboard EMMC mmcblk0 disk - usually partition 1, but depends on how you chose to partition the disk
> 
> If you are comfortable with using the Linux command line, and I will send you more instructions

Okay, after posting this, i played around with this idea that windows gives option to select os after installing it first on disk (followed by any linux distro) and that gave idea to install windows first (windows 10 x32 - safe boot disabled) successfully booted up on it, then again rebooted and tried installing the same ubuntu 16.04 with internet on(read somewhere that selecting the installation of 3rd party options gives it ability to add other more files crucial to linux) and while selecting the option to format the partitions, i chose "something else" option & removed all partitions created by windows(recovery, EFI, Microsoft Reserved (MSR) and Windows partitions), except one named "efi " & simply created swap & other linux partitions from freed partitions & continued the process.

After that completion, i selected the the "UEFI hard disk drives BBS priorities" & gave it had two options(aha! this is where windows compatibility with bios works best!) Options were 
-Windows boot manager
-**Ubuntu**
So i simply set the 1st priority to ubuntu & 2nd to windows (or u can select simply disabled!) & voila, ubuntu booted up without a hitch every single time.
Cons:
while installing windows, it took about 500~ mb of storage as "efi" (acc to linux!) otherwise, i completely had 30-31 gb for my linux installation.

I think this option is pretty sweet for people like me with less knowledge of ubuntu to install it quickly.

One small problem, connecting headphone (issue 36) makes sound on both laptop speakers as well as in headphones, whose temporary fix was to use " alsactl restore" but the sound is very low and distorted & close to not helpful.
Also, it seems that there is also no graphics compatible drivers (used this `sudo apt-get install xserver-xorg-video-intel` & driver were already there!) for this laptop on linux, that's why flux doesn't works & there is a slight lag every time i min/max a window.

but who cares i reaally want to know linux and hope this small work-around will initiate something somewhere, just as your repo did to me for taking steps to install linux in RDP in first place!

**Comment by tanmaydwivedi** [comment]
Also, quick update, i used your 16.04 iso instead of 18 because it said it had "no issues" but the same "Issue 36" is present, so i think that should be updated.
But correct me if i'm wrong & give me something for this very annoying problem.

**Comment by sundarnagarajan** [comment]
Glad to hear the F7-EFI-Boot option issue is resolved for you. Unfortunately, this seems to be an issue with the distribution, and not something that I can easily fix when remastering the ISO. I _plan_ to write a utility that can add an EFI boot option from within Linux, but:

- That will still be fixing the problem __after it happens__
- That will still work only for people who are familiar with Linux - will need to run a command line utility

Issue 36 is listed at the top of the main repository page under 'Open Issues'. It applies to all distro versions. The issue is because of:

- Sound driver for this model (_bytcht_es8316_) does not include detection of whether headphone is plugged in or not (GPIO read) not correct auto-muting of speakers when hedaset is plugged in (GPIO write)
- Several kernel versions ago, someone had posted a patch to do this on bugzilla.kernel.org, but that patch never made it to mainline, and mainline es8316.c was re-architected along the way enough that the patch no longer applies trivially.
- The RDP 1430 is not the only laptop to be affected by this. The Chuwi Hi12 is also affected, but the GPIO detection, reading and writing patch will need to be subtly different - see [here](https://github.com/kernins/linux-chwhi12/blob/master/sound/soc/codecs/es8316.c). This patch is also old and also will not cleanly apply on recent (4.19+) kernels.
- To fix this needs:
  - Work on extracting the relevant parts of the patched code and apply it successfully to a recent and maintained version of the driver
  - Submit patch to maintainer - difficult to find / get a response
  - Include in the patch a way to detect different laptop models (based on DMI) and apply different GPIO quirks in different cases
  - Make sure kernel maintainer accepts the patch - else future kernel maintenance / refactoring will break it again!

__no graphics compatible drivers (used this sudo apt-get install xserver-xorg-video-intel & driver were already there!) for this laptop on linux, that's why flux doesn't works & there is a slight lag every time i min/max a window__
    I have never experienced this or heard of this problem on the rDP 1430. It uses an Intel graphics chipset and it is auto-detected on all Ubuntu versions I have tried. The drivers are open source, and part of the mainline kernel and all required firmware should also be present in my remastered ISO. If you have more details, please open a separate issue for this.

**Comment by tanmaydwivedi** [comment]
> Glad to hear the F7-EFI-Boot option issue is resolved for you. Unfortunately, this seems to be an issue with the distribution, and not something that I can easily fix when remastering the ISO. I _plan_ to write a utility that can add an EFI boot option from within Linux, but:
> 
> * That will still be fixing the problem **after it happens**
> * That will still work only for people who are familiar with Linux - will need to run a command line utility
> 
> Issue 36 is listed at the top of the main repository page under 'Open Issues'. It applies to all distro versions. The issue is because of:
> 
> * Sound driver for this model (_bytcht_es8316_) does not include detection of whether headphone is plugged in or not (GPIO read) not correct auto-muting of speakers when hedaset is plugged in (GPIO write)
> * Several kernel versions ago, someone had posted a patch to do this on bugzilla.kernel.org, but that patch never made it to mainline, and mainline es8316.c was re-architected along the way enough that the patch no longer applies trivially.
> * The RDP 1430 is not the only laptop to be affected by this. The Chuwi Hi12 is also affected, but the GPIO detection, reading and writing patch will need to be subtly different - see [here](https://github.com/kernins/linux-chwhi12/blob/master/sound/soc/codecs/es8316.c). This patch is also old and also will not cleanly apply on recent (4.19+) kernels.
> * To fix this needs:
>   
>   * Work on extracting the relevant parts of the patched code and apply it successfully to a recent and maintained version of the driver
>   * Submit patch to maintainer - difficult to find / get a response
>   * Include in the patch a way to detect different laptop models (based on DMI) and apply different GPIO quirks in different cases
>   * Make sure kernel maintainer accepts the patch - else future kernel maintenance / refactoring will break it again!
> 
> **no graphics compatible drivers (used this sudo apt-get install xserver-xorg-video-intel & driver were already there!) for this laptop on linux, that's why flux doesn't works & there is a slight lag every time i min/max a window**
> I have never experienced this or heard of this problem on the rDP 1430. It uses an Intel graphics chipset and it is auto-detected on all Ubuntu versions I have tried. The drivers are open source, and part of the mainline kernel and all required firmware should also be present in my remastered ISO. If you have more details, please open a separate issue for this.

Hi again,
so i searched a little bit about what you said here & i found this [bugzilla ](https://bugzilla.kernel.org/show_bug.cgi?id=189261#c106l)kernel link in which these guys have successfully output sound on a cherrytail laptop (i think!) & reading down more i found a link to a github repo & the creator says that through that code (which he has on github) has sound only on headphone, but not on internal speakers of his laptop, which i think is okay for me...soo..can you look in to it so that same can be done on our RDP laptops, i'm waay more satisfied with **proper** sound only on headphones.
Here's the github [link](https://github.com/kernins/linux-chwhi12/blob/master/configs/audio/routing.howto)

**Comment by tanmaydwivedi** [comment]
okay, sorry again, it seems you've already given me this github link, so just hope that something can be done to do such that a proper sound output is there only on headphones, not in internal speakers, & that way only one will work which is great for me, else might need to switch to windows, which i reaaally don't want to do..
Hope something magical will happen from your reply :)

**Comment by sundarnagarajan** [comment]
If you want sound ONLY through a headset another option that will work for you will be to get a Bluetooth headset.

Regarding switching to Windows, I ABSOLUTELY ENCOURAGE you to switch to Windows if that is what you think is best for you. The mere thought of YOU switching to Windows does not have any effect on me.

**Comment by tanmaydwivedi** [comment]
C'mon bro...i really wanted to stick to linux, but things like this makes it difficult for a beginner to setup, and all i really wanted from you was the possibility of using full fledged Linux, as you've clearly committed your time in all of this, i thought you would be more enthusiastic towards a newcomer like me.

**Comment by tanmaydwivedi** [comment]
As for the bluetooth option, seems like it would require me buy some aux in bluetooth module, which tbh, for my student life is going to be a wait of a full loong month.

**Comment by sundarnagarajan** [comment]
Closed due to inactivity
