### ISSUE TITLE
BIOS Settings

### ISSUE THREAD

**Issue by jaredunn** [sundarnagarajan/rdp-thinbook-linux#9]
While trying to install Linux on the laptop, I messed up the some BIOS settings and got the device bricked.
After resetting the BIOS settings, my backlight stopped working. 

So could you post the values for the all BIOS settings under IGD - LCD Control? 

You can find it in Chipset -->North Bridge -->  IGD - LCD Control

Sorry to bother you about my problem and open this issue but your repository was the only source of information I could find about this laptop.

**Comment by sundarnagarajan** [comment]
No issues - I can post the BIOS settings. Which model of RDP Thinbook do you have - the 14-inch or 11.6 inch?

**Comment by sundarnagarajan** [comment]
I notice that the 11.6 inch does not have a top-level menu entry named 'Chipset' - BIOS is MUCH simplified on that model. So I assume you have the 14-inch RDP Thinbook.

On the 14-inch RDP Thinbook, the settings under Chipset --> North Bridge --> IGD - LCD Control are the following:

Force Lid Status --> On
BIA --> Auto
ALS Support --> Enabled
IGD Flat Panel --> Auto
IGD Boot Type --> Auto
MPIP DSI --> Disabled
Pannel Scaling (sic) --> Auto
GMCH BLC Control --> PWM-Normal
Enabled/Disabled PM Weights --> Enabled

Hope that helps

**Comment by jaredunn** [comment]
I have the same settings. It must be a hardware issue then. Anyway, thanks for the help.

**Comment by sundarnagarajan** [comment]
Some suggestions:

- Write down your current settings, and reset all settings in the UEFI firmware to default
- Try a different OS / Live ISO - since you can see the screen when going into the UEFI firmware, it doesn't look likely to be a hardware issue?
- If you are in India, RDP has quite a good service network

Best of luck!
